# Generated by Django 4.1.3 on 2022-11-23 17:40

import apptache.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptache', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apptache.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Prénom'),
        ),
    ]
