# Generated by Django 4.1.3 on 2022-11-29 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptache', '0002_alter_user_managers_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='status',
            field=models.CharField(default='En attente', max_length=56),
        ),
        migrations.CreateModel(
            name='SousTache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiquette', models.CharField(max_length=5)),
                ('couleur', models.CharField(max_length=56)),
                ('nom_tache', models.CharField(max_length=256)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('evolution', models.CharField(choices=[('ATTENTE', 'En attente'), ('COURS', 'En cours'), ('TERMINER', 'Terminer'), ('ABANDON', 'Abandon'), ('ANNULER', 'Annuler')], default=None, max_length=56)),
                ('executant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptache.projet')),
            ],
        ),
    ]
